### ISSUE TITLE
bib2gls (and other rules) missing from texlive 2017?

### ISSUE THREAD

**Issue by usharf** [cereda/arara#101]
Version: arara 3.0a

I've installed `arara` using tlmgr (on Ubuntu). It seems to have only installed some of the rules. For example, I don't see the script for `bib2gls`...

```sh
❯ ls '/home/uri/texlive/2017/texmf-dist/scripts/arara/rules' 
biber.yaml         lmkclean.yaml        make.yaml        sketch.yaml
bibtex.yaml        lualatexmk.yaml      nomencl.yaml     songidx.yaml
clean.yaml         lualatex.yaml        pdflatexmk.yaml  tex.yaml
dvips.yaml         luatex.yaml          pdflatex.yaml    xelatexmk.yaml
frontespizio.yaml  makeglossaries.yaml  pdftex.yaml      xelatex.yaml
latex.yaml         makeindex.yaml       ps2pdf.yaml      xetex.yaml
```

**Comment by usharf** [comment]
oops, sorry. saw now it's part of 4.0/

**Comment by cereda** [comment]
Hi Uri!

Oh it's completely my fault! Version 4.0 is not officially released, and it's been like this for a while. I am now finishing my thesis and hopefully I will be able to finally write the proper manual and submit the entire bundle to CTAN and hit TeX Live and MiKTeX. I have a planned talk about `arara` in TUG 2018 (to be held in Rio de Janeiro), so I have the moral obligation to release it. :wink: 

I never thought a thesis would take so much time and effort to write! I had to put version 4.0 on hold for more than 2 years! Since this new version is a qualitative and quantitative leap from version 3.0, it requires a complete rewrite for the manual. I am very excited because things are coming to an end (in a good sense!), so soon users will benefit greatly from the new features in the version 4.0!

For now, thank you very much for your patience and also for your appreciation, `arara` is nothing without the great users who decided to give my humble tool a chance! Stay tuned, I might have great news on the next weeks (and a certain release before July!).

All the best!

Paulo

**Comment by usharf** [comment]
Thank you very much for the quick response!
What would be the best way to install this beta (considering I'm using a manual install of TeX Live (rather than packages for Ubuntu)... 

p.s. Good luck with the thesis :)

**Comment by cereda** [comment]
Hello Uri!

My pleasure, it's always great to talk with our users! :wink: 

If you feel bold and adventurous enough (although version 4.0 is stable and the code is already declared gold), I can provide the deployment steps (as well as a binary) for making this version available in your system. However, I must admit that the rules are still to be revised and improved, and some new rules might appear soon. :smile: 

In general, `arara` requires a simple structure:

```
any dir/
├── arara.jar
└── rules/
   ├── animate.yaml
   ├── bib2gls.yaml
   ├── biber.yaml
   └── ...
```

What I do here is to use a bash script to wrap the `.jar` invocation and add its location to my path. That's exactly the same procedure TeX Live follows to make `arara` and other scripts/tools available. I can provide step-by-step instructions for you, just poke me!

Also, sorry for the delay in replying, sometimes I go offline to have some Pringles. :wink:

Cheerio!

Paulo
