### ISSUE TITLE
Error: wrong registry entry | missing arara.sty | installer for windows doesn't work

### ISSUE THREAD

**Issue by DiesDasJenes** [cereda/arara#102]
Hi,
today i tried to include arara in my LaTeX template for the first time with these three approaches :
1.  via the miktex package manager (\usepackage{arara})
2.  via the cross-plattform installer provided via the download page
3.  via the executable for windows

In the first approach i got very far besides the error that the arara.sty was missing. I copied it from somewhere in my root folder next to the index.tex and then i could start arara. I forgot where I copied the *.sty from. The problem with the first approach was that i got too many Option Clashes for the packages in my template. I dont get this errors when I use only pdflatex. 

The error i get using the second way is: 

> Process started:"C: \Program Files\arara\arara. exe" -v -l "Index".
> Launch4j: The registry refers to a nonexistent Java Runtime Environment installation or the runtime is corrupted.
> The system cannot find the specified path.
> Process ended with error (s)

I am using TexStudio and used this helpful post for configuring it for arara: https://tex.stackexchange.com/questions/313616/configuring-arara-in-texstudio-on-windows

My MWE is:
% arara: pdflatex
\\documentclass{article}
\\begin{document}
Hello, world!
\\end{document}

I have the JRE 8 and the jdk installed right now. 

The third approach could not install because of the same error: The registry refers to a nonexistent Java Runtime Environment installation or the runtime is corrupted.

I would have loved to work with arara.:heart: It looks so nice from the manual and the examples i found online. What can i do to fix the errors? Should i use a complete different approach?

**Comment by cereda** [comment]
Hello there! Thanks for the feedback!

First of all, I am deeply sorry if the following lines are written in a hurry, I am finishing my thesis as we speak, so I am bit clumsier than usual. :wink: 

Let me try to address a few important points.

1. You don't need `\usepackage{arara}` nor a corresponding `arara.sty` file because `arara` is not a package, it's a software, a command line program. `:)` I believe in this repository you will find a `.sty` file, but this is only used by me to compile my user manual, including the logo and other niceties. :wink: So no worries regarding packages.

2. The message issued by the `.exe` wrapper is indeed related to an absent Java Virtual Machine. As `arara` is written in Java, we really need a virtual machine installed in the operating system. I am not sure why the system complains about it, can you open your command prompt and see if you can issue `java` and get a proper output?

We will manage to solve your issues. :wink: 

Cheerio,

Paulo

**Comment by DiesDasJenes** [comment]
ok first off, i want to say: thanks for the tipp with the package manager. I really thought it would work like a package. I uninstalled the java jre i had on my pc. It was the newest one and reinstalled it. Now this worked and now arara also works. I love when i try something out for 5h and then make it work in under 5min with a tipp. :D 

Thanks for the help. :heart:

Now i have only one question left. How does the options work on pdflatex? Could you write a MWE example? I can't find a syntax explanation in the user manual on how to write the command with options.

best Regards,
Philipp

**Comment by cereda** [comment]
Hi Philipp!

Splendid, please let me know if you need any assistance, I will be more than glad to help! :wink: 

We have a [Gitter.im](https://gitter.im/cereda/arara) chat room in case you want an alternative for asking questions and providing feedback. I usually hangout there and a couple of `arara` friends as well. :duck: 

Cheerio!

Paulo
