### ISSUE TITLE
Spelling error in the manual

### ISSUE THREAD

**Issue by Krzmbrzl** [cereda/arara#108]
In the manual there is a spelling error right at the beginning of chapter 2 (p. 11). There it says `Spledid` when it should say `Splendid` (Notice the `n`).

I wanted to create a PR that fixes this problem but I couldn't find the respective part of the source code so I'm creating this issue instead.

**Comment by vermiculus** [comment]
FYI, https://github.com/cereda/arara/search?utf8=%E2%9C%93&q=spledid&type=

**Comment by Krzmbrzl** [comment]
Ah sure... How could I forget about GitHub's search function.

Though it confuses me that the only matches are in the `backup` folder. Does this mean that the issue has been resolved but the linked manual hasn't been updated yet?

**Comment by cereda** [comment]
Hello, friends!

Yes, the typo is in the `backup` directory, which I keep it for sentimental reasons. :wink: 

Since the current version of `arara` in TL and MT is version 3.0, I decided to keep the old sources. Sadly, I could not write the new manual based on the previous one because the tool changed *a lot*. It had to be written from scratch. Hopefully, I am in the middle of writing the new manual and I plan to release `arara` 4.0 in the middle of June, so fingers crossed! Then the `backup` directory will be no more. :wink: 

Sorry for the confusion...

Cheerio!

**Comment by cereda** [comment]
11b22b041f6ce926e4b9d68fa9a16b24432418f3 The (old) user manual is gone, long live the (new) user manual! Now we are in the official release countdown! :wink:
