### ISSUE TITLE
arara rule for knitr?

### ISSUE THREAD

**Issue by adamliter** [cereda/arara#112]
Hi @cereda! 🦆 I'm procrastinating, and so I'm getting to this a bit earlier than I had planned. In lieu of an email, I figured I'd open an issue here. Hope that's alright.

I started trying to write an `arara` rule for [`knitr`](https://yihui.name/knitr/), but I'm having some trouble because I don't really know how to construct the command.

Let me backup a bit, though, and explain how `knitr` works so that I can also flag some desiderata for what the rule should be able to do and how it should interact with other rules.

(Also, this is related to #46.)

# `knitr` overview

`knitr` is a tool that allows for writing inline R code in a `.tex` document. The associated file extension is `.Rnw`, and an `.Rnw` file (say `myfile.Rnw`) might look like this:

```tex
\documentclass{article}

\begin{document}

A graph about cars (Figure~\ref{fig:cars}).

<<cars, echo=FALSE, message=FALSE, fig.cap="Car graph", fig.lp="fig:">>=
library(ggplot2)
CarPlot <- ggplot() +
  stat_summary(data = mtcars,
               aes(x = factor(gear),
                   y = mpg
                   ),
               fun.y = "mean",
               geom = "bar"
               )
CarPlot
@

\end{document}

```

Everything in between `<<...>>=` and `@` is R code, and everything else is LaTeX. The idea is that you can produce a PDF from combining R code and LaTeX in a single document. The PDF is produced from an intermediate `.tex` file.

So the workflow would look as follows:

1. Edit the `.Rnw` file
2. Compile the `.Rnw` file to `.tex`; you could do this either by (a) starting an R session and `knit()`ing the file, or (b) running an R process via `Rscript`:

  a. 

```sh
$ R
R version 3.3.1 (2016-06-21) -- "Bug in Your Hair"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)
> library(knitr)
> knit('myfile.Rnw')
```
  b. 

```sh
$ Rscript -e "library(knitr); knit('myfile.Rnw')"
```

3. Compile the resulting `.tex` file with your favorite TeX engine to get a PDF, e.g.:

```sh
lualatex myfile.tex
```

# writing a `knitr` rule

So I'm trying to write a rule for `knitr` that uses `getCommand()` and the `Rscript` invocation mentioned above, but I'm having issues because of the quoting required by using `Rscript` to invoke an R process without starting an R session.

What's a good way to handle all of the quoting?

My first attempt was this, but this doesn't seem to actually expand the `@{file}` reference:

```yaml
!config
identifier: knitr
name: knitr
authors:
- Adam Liter
commands:
- name: knitr
  command: >
    @{
          return getCommand('Rscript -e "library(knitr); knit(\'@{file}\')"');
    }
arguments: []
```

My current attempt was to construct the command to be executed outside the scope of `getCommand()`: 

```yaml
!config
identifier: knitr
name: knitr
authors:
- Adam Liter
commands:
- name: knitr
  command: >
    @{
        command = 'Rscript -e "library(knitr); ';
        command = command.concat('knit(\'').concat(file).concat('\')"');
        return getCommand(command);
    }
```

But this results in a error:

```
Could not execute [Rscript -e "library(knitr);
knit('myfile.Rnw')"]. Error=2, No such file or directory
```

It actually seems like this is executing the correct command, so I'm not sure what is causing the no such file or directory error.

Can you give me any guidance here @cereda? I'm happy to write the rule and open a pull request (assuming you and the team are okay with incorporating a rule for `knitr` into `arara` directly, which you might not be okay with; see below), but I could use some guidance.

# Some desiderata for a `knitr` rule

To wrap it all up, there are a few things worth mentioning that would be nice to consider in writing a rule for `knitr`. The first relates to the workflow for `knitr` sketched above. The `.Rnw` file is the only file that the user should be editing, so it would be nice to go straight from `.Rnw` to `.pdf` without having to look at the intermediate `.tex` file or interact with it directly.

Currently this is not possible because the `(pdf|xe|lua)latex` rules use the file name, including extension. One workaround is to make use of the `files` parameter to these rules. That is to say, in `myfile.Rnw`, you could have these directives:

```tex
% arara: knitr
% arara: lualatex: { files: [ myfile.tex] }
```

But this hardcodes the name of the file into the directive, which seems hacky, in my opinion. 😝

Is there a better way to solve this given the capabilities of `arara`? Two other options that come to mind are:

1. Write custom `(pdf|xe|lua)latex` rules, but I assume these would never be incorporated into `arara`, so it would be up to the user (and any of the user's collaborators) to do this
2. Include the execution of `(pdf|xe|lua)latex` as part of the `knitr` rule

Of these, (2) seems the best, but then the rule becomes complicated if you want to allow selection of the LaTeX engine and allow for passing other command line options.

Furthermore, `knitr` is capable of producing other output formats than just `.tex`. For example, an `.Rhtml` file (*i.e.*, an HTML file with R code chunks) can be turned into an `.html` file by `knitr`, and an `.Rmd` file (*i.e.*, a Markdown file with R code chunks) can be turned into an `.md` file by `knitr`. If the `arara` rule for `knitr` were to accommodate these other uses, it would be best to decouple the rule that does PDF generation from the `knitr` rule.

Two last things. First, if a `knitr` rule is incorporated into `arara` itself (rather than having users write their own rules), you may need to consider adding the `.Rnw` (and `.Rhtml` and `.Rmd`) file extensions to `filetypes.` Ideally, `.Rnw` would take precedence over `.tex` because you would want `arara myfile` to look for directives in the `myfile.Rnw` file, not the `myfile.tex` file. I'm not sure if having something take precedence over `.tex` is something that you and the team are open to.

Second, and finally 🙃, there are several other options to the `knit()` command, so ideally these could be hooked into via the `parameters` of the rule. I can give more details about this later. This is already a lot to chew on, I know. 🐣 But I can work on this on my own if you're able to give me some direction on how to handle quotes and why I'm getting the no such file or directory error.

**Comment by adamliter** [comment]
Thanks for the help in the [TeX.SX chat](https://chat.stackexchange.com/transcript/message/46146500#46146500), @cereda 😸!

With your help, I've gotten close to having a `knitr` rule that accounts for all of the options to `knit()`:

```yaml
!config
identifier: knitr
name: knitr
authors:
- Adam Liter
- Paulo Cereda
commands:
- name: knitr
  command: >
    @{
        return getCommand('Rscript', '-e',
                          'library(knitr); knit("' + file + '", output = "' + output + '", tangle = ' + tangle + ', quiet = ' + quiet + ', envir = ' + envir + ', encoding = ' + encoding + ')');
    }
arguments:
- identifier: output
  flag: >
    @{
        if (isString(parameters.output)) {
            return parameters.output;
        }
        else {
            throwError('I was expecting a string name for the output file.');
        }
    }
  default: 'NULL'
- identifier: tangle
  flag: >
    @{
        if(isTrue(parameters.tangle) && parameters.output.equals('NULL')) {
            throwError('If you want to tangle the document, specify an output file.');
        }
        else {
            isTrue(parameters.tangle, 'TRUE', 'FALSE')
        }
    }
  default: ''
- identifier: quiet
  flag: >
    @{
        isTrue(parameters.quiet, 'TRUE', 'FALSE')
    }
  default: ''
- identifier: envir
  flag: >
    @{
        if (isString(parameters.envir)) {
            return parameters.envir;
        }
        else {
            throwError('I was expecting a string (that is evaluable as R code) specifying the environment in which code chunks should be evaluated.');
        }
    }
  default: 'parent.frame()'
- identifier: encoding
  flag: >
    @{
        if (isString(parameters.encoding)) {
            return parameters.encoding;
        }
        else {
            throwError('I was expecting a string specifying the encoding of the input file.');
        }
    }
  default: 'getOption("encoding")'
```

I really know nothing about Java, so if there are better ways to do anything, please make suggestions. 😉

One issue that I'm having with this rule currently is that when I leave `output` unspecified in the directive, I get the following error even though there is a default specified value for `output`:

```
[Error: could not access: output; in class:
java.util.LinkedHashMap]
[Near : {... rameters.tangle) &&
parameters.output.equals('NULL ....}]
```

Other than that, it seems like this rule works, though I haven't tested it extensively.

One further thing that would be nice would to be allow for arbitrary execution of R code before the call to `knit()`. I haven't yet tried to implement this, but I can do that.

For example, it would be nice to be able to run this before the call to `knit()`:

```r
knit_hooks$set(small.mar = function(before, options, envir) {
    if (before) par(mar = c(4, 4, .1, .1))
})
```

So the Rscript command would have to be: `Rscript -e "library(knitr); knit_hooks$set(small.mar = function(before, options, envir) { f (before) par(mar = c(4, 4, .1, .1)) }); knit('myfile.Rnw')"`. I haven't yet tried implementing support for this because I'm not sure if passing arbitrary R code through a directive parameter will cause any issues.

Aside from that, if you have suggestions regarding the other desiderata mentioned above, I'd appreciate it. And let me know what you and the team thinking about incorporating this into `arara`.

Thanks again for all of the help! 🙌

**Comment by cereda** [comment]
Hello @adamliter!

> I'm procrastinating, and so I'm getting to this a bit earlier than I had planned. In lieu of an email, I figured I'd open an issue here. Hope that's alright.

Of course it is! And procrastination is always a good thing. :wink:

> Let me backup a bit, though, and explain how knitr works so that I can also flag some desiderata for what the rule should be able to do and how it should interact with other rules.

Thank you! For me, being a `knitr` newbie, it is very important to understand the inner workings of such workflow. Your explanation is fantastic, and now we can work together in order to come up with an awesome `arara` rule!

Let's go!

> What's a good way to handle all of the quoting?

In previous versions of `arara`, we used plain strings to indicate command invocations and the tool had to employ guesswork to correctly parse arguments. I then realized this idea is the root of several issues reported by users. In other words, *automatic argument parsing* is definitely a bad idea, specially when handling complex scenarios like your `knitr` rule. From version 4.0, we marked this approach as deprecated and hopefully will be removed in future versions.

The best way of handling quotes is to rely on a high level structure with explicit argument parsing named `Command`. From the user perspective, a `Command` object is simply a good old list of `Object` objects, in which the list head (i.e, the first element) is the underlying system command, and the list tail (i.e, the remaining elements), if any, contains the associated command line arguments. The `getCommand` built-in method creates such object for us based on the provided arguments. For example:

```
getCommand('pdflatex', '--shell-escape', 'mydoc.tex')
```

The first element (namely, `pdflatex`) refers to the system command, and the two remaining ones (namely, `--shell-escape` and `mydoc.tex`) refer to the command arguments. The `getCommand` method then constructs a `Command` object for us.

> My first attempt was this, but this doesn't seem to actually expand the `@{file}` reference:

The reason for that is because you are already inside an orb tag! The `@{ ... }` is required only when you are in a plain string context:

```
Hi, my name is @{name}
```

However, if we are inside an orb tag already, it means we are dealing with the expression language itself, so we simply refer to the variable by name:

```
@{ 'Hi, my name is' + name }
```

Note that string concatenation can be done with either `+`  or `concat(...)`, both should work. I usually use them interchangeably with no issues.

> Is there a better way to solve this given the capabilities of `arara`?

The team is discussing the inclusion of parameter evaluation in the directive context, so this upcoming feature might be exactly what you are looking for! It might take a while though to reach the mainstream code, because we are studying ways of not breaking existing stuff. :wink:

> 2. Include the execution of `(pdf|xe|lua)latex` as part of the `knitr` rule

Yes, that would be my suggestion.

> Of these, (2) seems the best, but then the rule becomes complicated if you want to allow selection of the LaTeX engine and allow for passing other command line options.

Not too complicated. Take a look at, e.g, `frontespizio`, it is quite straightforward to make it happen. And since now we are using the folded style for writing scalars in the YAML file, the rule becomes cleaner, in my opinion. :wink:

> If the `arara` rule for `knitr` were to accommodate these other uses, it would be best to decouple the rule that does PDF generation from the `knitr` rule.

Rules are designed under the encapsulation notion, such that the direct access to internal workings of such structures is restricted. That also means that one rule should not, in theory, know about what happened before, in previous rules. However, there is a way to cheat `arara`, which is the use of a `Session` object. In practical terms, this particular object is a global, persistent map, acting as a a mechanism for data sharing across rule contexts. Personally, I would avoid this approach, as I am not exactly fond of context-aware rules. :wink:

I think it would be worth to include other output formats in the `knitr` rule, and even the execution of other commands, like a TeX engine, if you believe this idea would cover most of the scenarios. :wink:

> I'm not sure if having something take precedence over `.tex` is something that you and the team are open to.

I think there is always room for discussion, so do not worry too much. :wink: Also, since version 4.0 supports local configuration files, one could simply add the patterns to the root of a project and `arara` would work as expected, without the need of having a global configuration file.

> I really know nothing about Java, so if there are better ways to do anything, please make suggestions. :wink:

Neither do I. :wink:

> One issue that I'm having with this rule currently is that when I leave `output` unspecified in the directive, I get the following error even though there is a default specified value for `output`:

The reason for that is because `output` is not yet processed. It is quite tricky to mix different argument checks. One way of doing what you want is changing that offending line by:

```
if(isTrue(parameters.tangle) && !parameters.containsKey('output')) {
...
}
```

Since you are evaluating the `tangle` argument, you are certain that it exists. However, nothing can be said about `output`, that is why we need to check if it exists in the map. In this case, note the negation `!` before the method call, so we check if `output` is absent from the parameters.

I usually leave cross-argument validation to the `command` context, as everything is resolved in there, and keep simple verifications to the `flag` context. But that is basically my style of doing things. :wink:

> One further thing that would be nice would to be allow for arbitrary execution of R code before the call to `knit()`. I haven't yet tried to implement this, but I can do that.

In theory, it should work, but I don't think the directive parameter handler would gracefully allow such entries. Perhaps passing arbirary code through directive parameters might not be a good idea. I will think of something along those lines.

> Aside from that, if you have suggestions regarding the other desiderata mentioned above, I'd appreciate it. And let me know what you and the team thinking about incorporating this into `arara`.

I believe we are now reaching a very powerful and stable `knitr` rule, so it might be a good addition to the default rule pack of `arara`. I will take a look at your code later on and propose some improvements, but so far I am glad it works. :wink:

All the best!

Paulo

**Comment by adamliter** [comment]
Thanks @cereda! This was all really helpful.

Regarding:

> > 2. Include the execution of (pdf|xe|lua)latex as part of the knitr rule
>
> Yes, that would be my suggestion.

Thinking about this a bit more, this is still not ideal because you may also want to process the resulting `.tex` file with, among other things, `makeglossaries`, `biber`, *etc.*. Bundling all of these potential things into a single `knitr` rule seems suboptimal, especially because (I think?) it would preclude making use of the conditional checks that you can now do with `arara` 4.0 in the directives.

For example, it'd be nice to be able to have the directives in `myfile.Rnw` look like this:

```tex
% arara: knitr
% arara: xelatex
% arara: biber
% arara: makeglossaries
% arara: xelatex while found('log', 'undefined references')
```

If the alternative is something like this:

```tex
% arara: knitr: { engine: xelatex, bibliography: biber, makeglossaries: yes }
```

it seems like you would lose the ability to sensibly check stuff conditionally in the directives, right? (You'd just end up rerunning the whole rule in its entirety, I think.) Of course, the rule could be written to be smart and do such checks itself, but it seems more in line with the spirit of `arara` to have this stuff specified in the directives. The user can then clearly see the compilation steps.

So perhaps for the time being, the best solution just is to hardcode the file name in the (pdf|xe|lua)latex directive like so:

```tex
% arara: knitr
% arara: xelatex: { files: [ myfile.tex ] }
% arara: biber
% arara: makeglossaries
% arara: xelatex { files: [ myfile.tex ] } while found('log', 'undefined references')
```

Do you have any further thoughts or suggestions? I'm still happy to open a pull request for a `knitr` rule, but if you have any further feedback, I'd appreciate it. I'll try to put together a pull request in the next day or two, which you and the others can take a look at and decide if this is something that you want to incorporate into `arara`.

**Comment by TheTeXnician** [comment]
arara v5.0 will feature a knitr rule inspired by your postings above. The release is scheduled to happen before the DANTE Frühjahrstagung.
