### ISSUE TITLE
isBoolean method doesn't detect boolean parameters

### ISSUE THREAD

**Issue by ArTourter** [cereda/arara#115]
In the rule I am writing, I have a fairly complex set of parameters which depending on the value of another parameter needs to either be a boolean or a string.

I was trying to check the type of the parameter to make sure it was correct for the value of the other parameter, but parameters seem to always be detected as a string, even is the value is yes, 1, on, true, no, 0, off, or false.

I could check the string value directly but that seems messy. Alternatively, I could insist the user only use "y" or "n" for these parameters as this is what qpdf expect as boolean values but it doesn't match the syntax used in arara so I would rather not.

**Comment by cereda** [comment]
`isBoolean` actually refers to literal type checking, not semantic values like `yes` or `not`. If a variable holds a value of boolean type, `isBoolean` will return `true`. For example (MVEL):

```java
a = true;
b = 1 == 2;
c = 'true';
d = 'yes';

System.out.println(isBoolean(a)); // true
System.out.println(isBoolean(b)); // true
System.out.println(isBoolean(c)); // false
System.out.println(isBoolean(d)); // false
```

If I recall correctly (even I don't remember my own stuff), `isTrue` and `isFalse` check semantic values, so `yes`, `no`, `on`, `off`, `0`, `1`, `true` and `false` are evaluated accordingly. For example (MVEL):

```java
a = 'yes';
b = 'no';

System.out.println(isTrue(a)); // true
System.out.println(isFalse(b)); // true
```

However, if memory serves, a value other than what we call a natural boolean in the manual raises an exception from `isTrue` and `isFalse` methods. In other words, `isTrue('foo')` will raise an exception. This is by design: a parameter that should be a boolean must be handled as such.

A possible way to handle this scenario in a broader sense (MVEL):

```java
if ([ 'yes', 'no', 'true', 'false', '0', '1', 'on', 'off' ]).contains(value)) {
    // value is within the natural boolean range
}
else {
  // value is not a natural boolean
}
```

Hope that helps. :wink:

**Comment by TheTeXnician** [comment]
There has been no reaction whether the explanation helped or not. So this will be closed waiting for feedback.
