### ISSUE TITLE
Check for changes in subdirectory

### ISSUE THREAD

**Issue by befelix** [cereda/arara#121]
I am wondering how to check for changes to files within a directory. Something like `% arara: pdflatex if changed(toFiles('sections/*.tex'))` or even something that works recursively.

I know how to do this for individual files (#82), but couldn't figure out how to do this more generally without having to modify the code for every new file.

Thanks for your help!

**Comment by cereda** [comment]
'ello! :wink: 

> **Note:** This is _really_ a neat idea and a good addition to a new revision. It really never crossed my mind about checking multiple files at once! I might give a bit of thought since there are some tricky scenarios in which I need to offer some room for the user (right now, I am thinking of short circuit evaluation). Anyway, thank you very much for bringing this idea up!

So I read your comment and thought, _well, it might be a bit hackish for now, but I could use some lambdas and whatnot in order to provide a sensible answer_. Looks like Monday wouldn't be Monday if I could get things easily done. :rofl: 

I need to investigate further, but it seems that the underlying expression language used by `arara` has some limitations regarding the use of lambdas and other syntactic features. This means that my one line, dirty and cool solution won't be achieved, at least for now.

The only way to achieve this, as things are right now, is to move the check inside a proper rule. There I think I can code a sensible solution for your scenario. I understand it might be a nuisance since we move a conditional from the directive scope to the rule counterpart, but as a compromise act, we could come up with a more generic rule that can mitigate some of these limitations.

Would a new rule be an acceptable workaround for your scenario? If so, we can construct one. :wink: 

Cheerio!

Paulo

**Comment by befelix** [comment]
Thanks a lot for the fast reply! I think a new rule would certainly be acceptable. 

From my perspective the cleanest solution would be to make `changed` accept `List<File>` objects that can be generated with `listFilesByExtensions`. Alternatively one could construct that if there were extended logic/mapping functions - something along the lines of `if all(map(unchanged, List<File>))`. 

Though I'm not really familiar enough with the guts of `arara` to have a good idea what the best solution is :)

**Comment by cereda** [comment]
I will try to come up with a sensible rule in the next hours, then. :wink: 

Your proposal looks great, indeed, and `all(...)` and `some(...)` sparkled some ideas on what can be implemented. To be honest, lambdas would help us greatly in here (I originally thought something along the lines of

```tex
% arara: pdflatex if Arrays.asList(toFile('tests/').
% arara: --> listFiles(f -> f.endsWith('.tex')).
% arara: --> stream().anyMatch(f -> changed(f))
```

which is, from the top of my head, valid Java 8+ code), however the underlying expression language is complaining about it. You really caught me off guard, so I need to investigate further. :wink:

I will keep you informed of my progress, don't worry. And a rule will be available pretty soon!

**Comment by cereda** [comment]
Hi, sorry for the delay! Here's my proposed rule:

```yaml
!config
identifier: compile
name: Conditional document compilation
authors:
- Paulo Cereda
commands:
- name: The engine
  command: >
    @{
        command = getCommand(engine, interaction, draft,
                  shell, synctex, options, file );
        if (isEmpty(directory) || isEmpty(patterns)) {
            return command;
        }
        else {
            entries = listFilesByPatterns(toFile(directory),
                      patterns, recursive);
            for (entry : entries) {
                if (changed(entry)) {
                    return command;
                }
            }
            return true;
        }
    }
arguments:
- identifier: recursive
  flag: >
    @{
        isTrue(parameters.recursive)
    }
  default: >
    @{
        return false
    }
- identifier: patterns
  flag: >
    @{
        if (isList(parameters.patterns)) {
            return parameters.patterns;
        }
        else {
            throwError('I was expecting a list of patterns.');
        }
    }
- identifier: directory
  flag: >
    @{
        parameters.directory
    }
- identifier: engine
  flag: >
    @{
        if ([ 'pdflatex', 'pdftex', 'tex', 'latex', 'luatex', 'lualatex',
              'xetex', 'xelatex' ].contains(parameters.engine)) {
            return parameters.engine;
        }
        else {
            throwError('The provided engine value is not valid.');
        }
    }
  default: pdflatex
- identifier: interaction
  flag: >
    @{
        if ([ 'batchmode', 'nonstopmode', 'scrollmode',
              'errorstopmode' ].contains(parameters.interaction)) {
            return '--interaction='.concat(parameters.interaction);
        }
        else {
            throwError('The provided interaction value is not valid.');
        }
    }
- identifier: shell
  flag: >
    @{
        isTrue(parameters.shell, '--shell-escape', '--no-shell-escape')
    }
- identifier: synctex
  flag: >
    @{
        isTrue(parameters.synctex, '--synctex=1', '--synctex=0')
    }
- identifier: draft
  flag: >
    @{
        isTrue(parameters.draft, '--draftmode')
    }
- identifier: options
  flag: >
    @{
        if (isList(parameters.options)) {
            return parameters.options;
        }
        else {
            throwError('I was expecting a list of options.');
        }
    }
```

That's actually a big rule. :wink: The idea was to incorporate the typical options for the engines, and a new parameter named `engine` in which you can specify the actual engine to compile the document (it defaults to `pdflatex`). I added three more parameters that relate to our conditional compilation:

- `directory`: that's the base directory in which the file search will be performed. In here, we do not add the file patterns yet, just the base directory itself. For example:

    ```tex
    directory: 'sections/'
    ```

- `patterns`: as the name implies, this parameter holds the file patterns to be applied during the search. It takes a list and accepts the `*` and `?` wildcards. For example:

    ```tex
    patterns: [ '*.tex' ]
    ```

- `recursive`: and at last but not least, this parameter holds a boolean value indicating whether  the search should be recursive. It defaults to `false` (only the base directory is inspected), and any natural boolean can be used as value. For example:

    ```tex
    recursive: yes
    ```
A sample preamble would be:

```tex
% arara: compile: {
% arara: --> engine: pdftex,
% arara: --> directory: 'sections/',
% arara: --> patterns: [ '*.tex' ],
% arara: -->  recursive: yes
% arara: --> }
```

That said, I don't know if my logic is the best one. Perhaps we could move the `return` statement out of the `for` loop and use a `||` operation, so all files are inspected, and we can get a better result, not having to resort o subsequent compilations. Something along the lines of replacing:

```
            for (entry : entries) {
                if (changed(entry)) {
                    return command;
                }
            }
            return true;
```

by:

```
            check = false;
            for (entry : entries) {
                check = changed(entry) || check;
            }
            return check ? command : true;
```

It looks way better. Also note `check = changed(entry) || check;` as the term order matters! Due to the short circuit nature of `||`,  I forced `changed(...)` to be processed first, so we can ensure all file statuses are updated. It took me a couple of minutes to figure that out! :wink: 

Well, for starters, I think we have a nice rule framework to improve upon. Please let me know if I can enhance the current rule in order to meet your scenario. :wink: 

Cheerio!

Paulo

**Comment by befelix** [comment]
Wow! Thanks a lot for your help!
