### ISSUE TITLE
Instructions on compilation

### ISSUE THREAD

**Issue by jonasstein** [cereda/arara#122]
Please add instructions, on how to compile arara and which dependencies are required.

**Comment by TheTeXnician** [comment]
Basically, you need a working Maven installation. Afterwards a simple `mvn package` will do the job, because it will also fetch the dependencies from `pom.xml`.
The whole process is detailed in chapter 8 of the manual ("Building from source"). What is missing for you?

**Comment by jonasstein** [comment]
Distributions could be interested in distributing arara. In the case of Gentoo we want to compile the source. The source package must not pull external sources for security reasons.
The package manager has to handle missing dependencies.

**Comment by TheTeXnician** [comment]
Well, my question was more or less intended to ask what kind of information for compiling arara you are missing. As it stands your title asks for instructions on the compilation of arara. This is detailed in chapter 8 of the manual. It is also quite clear which dependencies arara has because apart from the Java installation (and for compiling also Maven) you need the libraries referred to in `pom.xml`.

You seem much more interested in having a Java build file which does not need to fetch dependencies using Maven than obtaining information on how it is compiled. Sorry for the noise.

**Comment by TheTeXnician** [comment]
The manual contains all relevant information for packaging up `arara` as JAR and the `pom.xml` file (in future releases the `build.gradle.kts` file) all dependencies. So I'm closing it for now.
