### ISSUE TITLE
Add --credits in CLI

### ISSUE THREAD

**Issue by pablgonz** [cereda/arara#134]
Hi, I have a little doubt and a request, I know that the main author of `arara` is Paulo, but, in the description (`README.md`) you can read that there is a whole team behind this great work. 
Currently `arara --help` shows the following lines:
```
arara 4.0 (revision 2)
Copyright (c) 2012-2019, Paulo Roberto Massa Cereda
All rights reserved
```
maybe it'll be nicer:
```
arara 4.0 (revision 2)
Copyright (c) 2012-2020, The arara team.
All rights reserved
```
and the option `--credits` is added and the original author and team members are named.
Just as an idea.
Saludos

**Comment by cereda** [comment]
Hey Pablo!

For the upcoming version 5.0, `arara` will be under [Island of TeX](https://gitlab.com/islandoftex), which is an organisation created by my friends and yours truly to hold our beloved TeX-related projects (see e.g, [TeXplate](https://gitlab.com/islandoftex/texplate)). The development header is currently displayed as:

```
arara 5.0
Copyright (c) 2012-2020, Island of TeX
All rights reserved
```

So half of the issue is contemplated. :wink:

Regarding the `--credits` option, it is surely an interesting idea! We will discuss and report back. It is also interesting to note that `arara` is about to be reallocated to a new home at [GitLab](https://gitlab.com/), under the IoT umbrella. We will soon publish the new repository and keep our GitHub home as a mirror. We will still cover issues and suggestions, so do not worry about this migration. We just found a bigger nest for our parrot. :wink: 

Cheerio!

Paulo

**Comment by pablgonz** [comment]
Great, it would be nice to see something along the lines of `luatex --credits`. A change of house for `arara` is a good gift for this 2020.
Saludos

**Comment by TheTeXnician** [comment]
We will ship the first part in arara v5.0 before the DANTE Frühjahrtstagung end of the month. But currently, the team does not see the need for such an extensive credits option (listing dependencies and their dependencies is something we do not want to keep and listing only the team might be an enhancement to the version flag in future releases).
