### ISSUE TITLE
arara.sh is behaving wrong

### ISSUE THREAD

**Issue by onekk** [cereda/arara#135]
when using arara.sh from TexWorks, using the command option:

`/usr/local/texlive/2019/texmf-dist/scripts/arara/arara.sh`

it raise an error about command not found

it is examping basename as `arara.sh`

If I change the script name and put simply `arara` it is working again.

I'm using Texlive from a tlmgr installation, not using the Distribution package.

Regards

Carlo D.

**Comment by nlct** [comment]
TeX Live creates symbolic links in the `bin` architecture sub-path to applications in `scripts` with the extension omitted. For example, `/usr/local/texlive/2019/bin/x86_64-linux/arara` is a symlink to `/usr/local/texlive/2019/texmf-dist/scripts/arara/arara.sh`. This means that you simply have to type `arara` not `arara.sh` on the command line because the `PATH` environment variable should include the `bin/`_arch_ path not the `scripts` path. In general, it's best to use the `bin` path rather than the `scripts` path if you have to specify the full pathname. (This isn't specific to arara. There are other bash scripts that also expect to be called via the symbol link.)

@cereda Perhaps 
```bash
scriptname=`basename "$0"`
```
should be changed to 
```bash
scriptname=`basename "$0" .sh`
```

**Comment by onekk** [comment]
OK, sorry for the inconvenience, I have followed a hints on activating arara for TexWorks, and this hint used the path in the scripts and not those in the bin dir.

Regards

Carlo D.

**Comment by nlct** [comment]
It's useful to have a record here in case anyone else has the same problem.

**Comment by cereda** [comment]
Ciao, Carlo!

Thanks for the report, it's much appreciated!

I am almost sure this issue is connected to [this message of mine in the TeX Live mailing list](https://tug.org/pipermail/tex-live/2019-November/044473.html).

We will investigate further. Grazie mille! :wink: 

@nlct I still believe TeXworks is the culprit here, as in _not our fault_ :wink:. We could raise the concern with Karl and Norbert and check if they have any pointers for us...

**Comment by onekk** [comment]
I'm not clear enough in the last message.

I've resolved using the invocation of arar in Texwork using:
`arara` without specifing the path

and putting 
`$basename`

in the "Arguments" frame (hope this is the exact translation, I'm using an Italian localized version of Texwroks)

Hope it will be useful, maybe to write in the wiki some hint about the use of arara in Texworks.

Using Arch Linux (ArtixLinux to be exact) for TexWorks, it is not heavily patched (relatively to some other distributions).

Regards

Carlo D.

**Comment by cereda** [comment]
Thanks, Carlo! The previous version had a section in the user manual for editor integration. It seems it would be great to bring it back. :wink: 

I think I use `$fullname` in TeXworks, but I will investigate.

For now, thank you very much for the report!

**Comment by TheTeXnician** [comment]
In version 5.0 (in MikTeX and TL pretest) the suggested change from https://github.com/cereda/arara/issues/135#issuecomment-585638437 has been integrated (see ece4b038f841e3de1245730e2c84da2986bd4c6d). Does this fix your issue?

**Comment by TheTeXnician** [comment]
I'll close that issue for now. If it isn't fixed in version 5.0.2, please reopen and describe what's not working.
