### ISSUE TITLE
pdflatex is not terminated when typesetting fails and verbose mode is activated

### ISSUE THREAD

**Issue by Keex0r** [cereda/arara#139]
Hello,
I have been encountering an issue when I enable Verbose output mode in Arara, when compiling a TeX document from the TeXworks UI. I have enabled Verbose mode so I receive the error message in case something is wrong in my document.

I have been using these Arara settings:

```
% !TEX TS-program = Arara
% !TEX encoding = UTF-8 Unicode

%%% Compilation by arara
% arara: pdflatex: { draft: true }
% arara: biber
% arara: pdflatex: { synctex: true }
```

Here is what happens:
In case my document is correct, everything works fine. If I have an error in there, e.g. a wrong image filename, and then run the typesetting, pdflatex will do its thing until the error is encountered. The typesetting then sits there and waits, until I cancel it. Now, I get a warning that an aux file is corrupt, and I should clean them, but this fails, because the pdflatex process is still active in the background. When I don't clean the aux files, the compilation won't work even if I fix the error in the document. So I have to kill the pdflatex process in the task manager, clear the aux files, then compile again (after fixing the error).

So this is less than smooth. However, when I disable the -v option in Arara, it will correctly report a FAILURE for pdflatex, and everything is fine. The pdflatex process is terminated and no problems with the aux files occur, so I can just fix the error and typeset again. However, in this way I don't get a message where the error is, which is also not ideal.

I tried typesetting with pdflatex alone, and here the aux files also get corrupted, but the pdflatex process is nevertheless terminated so after a cleaning of the files everything is fine again.

I am using TeXworks under Windows 10 (2004).

Please let me know if I can add any information to narrow down the problem. I am quite new to the whole TeX stuff, so forgive naive descriptions.

Thanks!
Jens

**Comment by TheTeXnician** [comment]
Many thanks for your report and welcome to the world of TeX and arara :slightly_smiling_face: 
This is related to #138 and seems to be specific to Windows' process management (can't reproduce on Linux here).

We are tracking this issue at https://gitlab.com/islandoftex/arara/-/issues/39 (development has moved to GitLab some time ago) and plan to fix this in the v6 release (TL2021 because we do not ship breaking changes within one TL release cycle; we consider this breaking because it is not documented that arara will kill processes waiting for input on exit).

You are right that this only happens in verbose mode because there we intentionally redirect the programs output *and input* to the editor/terminal. That is arara is still running but idle waiting for another process to fetch input when TeX presents its error prompt. Without verbose mode it is intended that you are only able to get messages from the log file (which you can enable with the `-l` option). These fundamental execution modes of arara have their quirks, that's right.

That said, your approach to killing is definitely not a good idea. Whoever kills a TeX process while running will cause corrupted auxiliary files (independent whether TeXworks, arara or you start the TeX process). The deletion of these files is just a workaround to properly terminating TeX. And with properly terminating I mean that when an error occurs you should type `x` into TeX's prompt to let it finish its cleanup. In 90% of the cases you do not even need to run the aux file cleanup afterwards.

If you are interested in more technical points, there's also https://github.com/cereda/arara/issues/138#issuecomment-603242488 explaining the team's position.

To wrap up: Thanks for reporting, we are aware of this problem and will fix it in version 6 but as this will take some time, you may need a workaround like gracefully terminating TeX.

**Comment by Keex0r** [comment]
Thanks a lot, TheTeXnician, for the thorough answer and the continued work. I haven't seen the already open issues that address this.
With your descriptions I just realized that the window in TeXworks is a terminal that accepts commands and typing `x` is a great point - I didn't realize that pdflatex is sitting there, waiting for me to tell it what to do. That's a nice workaround for my troubles here - typing x I can do. :-)

Thanks for all the effort!

**Comment by cereda** [comment]
Wow, you guys are fast. :wink:

It's worth mention that TeX engines usually prompt the user for interaction in the event of an error. We can alter this behaviour by providing a certain value to the `interaction` key. In this particular scenario, use the `nonstopmode` value, so there will be no possibility of user interaction:

```tex
% arara: pdflatex: { interaction: nonstopmode }
```

Cheerio!

**Comment by Keex0r** [comment]
Nice to know, Cereda, thank you!
