### ISSUE TITLE
Rules doesn't work for Cygwin-users -- New way needed

### ISSUE THREAD

**Issue by marcodaniel** [cereda/arara#62]
Instead of the direkt symlink pdflatex we have to use `pdftex "--fmt=pdflatex"`

See http://chat.stackexchange.com/transcript/message/19336610#19336610

**Comment by cereda** [comment]
I've raised this in the [Apache Commons mailing list](http://www.mail-archive.com/user@commons.apache.org/msg09788.html), let's see what they tell me.

To be completely honest, I'm really not inclined on changing the rules to use the `--fmt` flag instead of the current mnemonics. As far as I've read about it, Cygwin has some odd behaviour towards command line commands, and besides, it's a emulation layer added on top of an operating system; it's already troublesome to deal with Windows things on themselves.

If there's a way to detect a Cygwin execution, I'll provide `isCygwin()` then the flag can be used; otherwise, I'll stick with the mnemonics. `:)`

**Comment by cereda** [comment]
Of course, we can summon the high `arara` council (Brent and Nicola) and ask for their opinions. This is gonna be a disaster since Brent uses Cygwin as well. `:)`

**Comment by cereda** [comment]
Something came to my mind! We need to check if this behaviour happens with the new version because the way commands are now built is way more robust. Maybe things already work and we are worried for nothing. `:)`

**Comment by vermiculus** [comment]
An `isCygwin` flag might not be a bad idea regardless :smile:

**Comment by cereda** [comment]
Indeed, I'm just not sure how to detect this. `:)` In any case, one for version 5.0, unless it's a quick fix. :laughing:

**Comment by vermiculus** [comment]
`uname` ?

**Comment by cereda** [comment]
`uname` might be the pragmatic way of solving it, but I am not really sure if it works all the time. I would need a machine with Windows, so I could test this contraption. :smile:

**Comment by vermiculus** [comment]
@cereda Give me ideas and I'll test them :smile:

**Comment by cereda** [comment]
I am very happy with the final code of d68716e2eaef394963627ed090c7d2cb8365f5fe, since the system call is only done on demand and once, so no performance drops. Why people use it instead of a real operating system? :hamburger:

**Comment by vermiculus** [comment]
Alas, the business world has realized their error, but it is now too late to turn back. We're in too deep.

**Comment by cereda** [comment]
@vermiculus We should profit on this. :heart:

**Comment by cereda** [comment]
You guys made me do this (Windows XP on top of Virtual Box running in my Mac):

![prompt](https://cloud.githubusercontent.com/assets/302062/7924983/88a350bc-0896-11e5-900c-cbe25ef41cef.png)

![cygwin](https://cloud.githubusercontent.com/assets/302062/7924985/8ffbe2c0-0896-11e5-93aa-c339a011fa98.png)

I found out a couple of things when working on this solution:

- Cygwin appends the Windows path to its own path. That said, although Cygwin says its `pdflatex` (usually located at `/usr/bin/pdflatex`) is the first in the path priority, the one executed is from the Windows path (say, MiKTeX or TeX Live, depending of who comes first in the path). When I removed the TeX reference from my Windows path, Cygwin started looking at his own path and I finally could reproduce the issue reported by David. I suspect the list of file extensions that Windows considers to be executable (good old `PATHEXT`) might be the culprit here; maybe a symlink has a lower priority than a binary, that's why Cygwin favours an `.exe` (only a wild guess).
- In a situation that TeX Live or MiKTeX is in the path and either one is called inside Cygwin, the issue is not reproduced. It seems the only way to get this behaviour is to rely on Cygwin's TeX Live flavour only.
- As seen in the screenshots (and in a couple of previous experiments of mine), `arara` is able to detect if being called inside Cygwin or not. I think we could keep the `--fmt` parameter only for Cygwin, even if TeX Live or MiKTeX is being used inside it, since it does no harm. For other contexts, I would prefer the `pdflatex` mnemonic.

That's it, good job, friends! :smile:
