### ISSUE TITLE
What does it do?

### ISSUE THREAD

**Issue by mikkelam** [cereda/arara#66]
What does this tool actually do? The readme is very unspecific. I fell over a link to this project, yet I am unable to figure out what it is for. 

Just thought you should consider adding some example or a better description.

**Comment by cereda** [comment]
Hello! `:)`

`arara` is an automation tool focused on TeX workflow. It works on reading metadata in comments in the source code. For example, the following code illustrates a simple usage:

```tex
% arara: pdflatex
\documentclass{article}
\begin{document}
Hello world!
\end{document}
```

The `% arara: pdflatex` line contains a directive, which tells the tool what to do with the source file and in which order to follow. It's like writing a recipe in the form of special comments in the source code and then later on have someone (the tool) following it. `:)`

Thanks for the hint, I will add an example in the `README` soon.

All the best!

Paulo

**Comment by Superbest** [comment]
I was confused similarly to mikkelam. The example doesn't really help - can't you just run pdflatex on the file and do away with the comment?

I have found an arara manual that claims arara is useful for running bibliography, glossary and so on tools in sequence. But doesn't TexStudio and similar tools already do that? Can't the sequence of Latex calls be implemented as a shell script? Is arara meant as an alternative to these, or does it provide some functionality not otherwise available?

I feel like a better explanation of what arara does and what it's for might be worth adding to the Readme, since currently tex.stackexchange.com links to this page.

**Comment by egeerardyn** [comment]
@superbest: yes, you can get the same or similar results with a shell script, batch file, latexmk, make file, ... or using a Latex editor as what you get with arara.
Personally, I think the advantage of arara is that it is platform independent (unlike shell scripts, make files and batch files) and that it is a human readable definition within your latex file. So you don't need to distribute other files and even people that don't use arara can easily see how the file should be compiled.

But ultimately, whichever build tool you use, depends on your own preference.

**Comment by cereda** [comment]
Hello, friends.

@Superbest: Thanks for raising these questions, they are very important for us as a project and hopefully I will try to address them. :wink: 

> can't you just run pdflatex on the file and do away with the comment?

Yes, but it would defeat the purpose of showing a minimal working example using a directive. :wink: I believe the example is more of a first contact of how `arara` works. It has a comment and some code. The comment has a special form which is exploited by `arara` in order to discover what to do. So, the example might not do something major, but I think it conveys the idea.

In my humble opinion, there's another important concept being introduced in that particular example: it tells us exactly what tool is going to process the source. Personally, I believe a significant number of people using TeX and friends right now does not know exactly what they are doing, they just click a button in their favourite IDE and let the program decide or guess what to do and hope for the best. When you actually understand what and why you are doing, there's a personal growth that makes things easier in the future. :wink:

> I have found an arara manual that claims arara is useful for running bibliography, glossary and so on tools in sequence.

Yes, that is correct. :smile: 

> But doesn't TexStudio and similar tools already do that?

Some IDE and text editors do that, yes. How they do that? There is a concept called *standard user behaviour*, which aims at providing a set of features designed for what they believe is the most common usage scenario. Most of these tools employs this idea. Sadly, the TeX workflow is not as easy it seems, and delegating this workflow solely to your editor is risky when you need to invoke `biblatex`, `makeglossaries`, remove auxiliary files or any other task which is not part of the average bear toolbox.

If you know the exact steps your editor is doing (and of course, you agree with these steps), there is no problem at all in using this feature and forget about `arara`. :wink:  But if one blindly believes that a *build* button in an IDE or text editor will correctly guess the proper workflow every time, disaster and frustration will follow. Surely, learning the correct workflow requires effort, and most users just wants their paper or thesis to be compiled. This means that using `arara` properly comes at a cost. Some say specifying the steps in a source code is bad, I say it is good. One person's bug is another person's feature. :smile: 

> Can't the sequence of Latex calls be implemented as a shell script?

Yes, it can, as well as using makefiles, shell scripts, batch files and build scripts like Ant, Maven, SBT and Gradle. The list is endless. :wink: 

> Is arara meant as an alternative to these, or does it provide some functionality not otherwise available?

It is an alternative, and I never had the intention of it being a replacement. :wink: I wouldn't say `arara` has more functionality than the others, but it might offer a more friendly interface. Some aspects I like include a more readable syntax and being document-based, as @egeerardyn mentions. Your mileage might vary. :wink: 

> I feel like a better explanation of what arara does and what it's for might be worth adding to the Readme, since currently tex.stackexchange.com links to this page.

Sure, I will see what I can do. :wink: My real problem at the moment is the lack of time, so the project is going at a very slow pace at the moment. I never thought a PhD adventure would consume so much time! :wink:

**Comment by Superbest** [comment]
@cereda 

>So, the example might not do something major, but I think it conveys the idea.

Oh, definitely. But I think it would be neat to have a (maybe second?) example that shows off an `arara` trick that would be difficult to do otherwise. In fact, why not do the same thing in alternative ways so visitors can see for themselves how `arara` is helpful? I think it would help if the example was a bit more complicated - I suspect it's the less simple scenarios that are where `arara` really shines.

>Personally, I believe a significant number of people using TeX and friends right now does not know exactly what they are doing, they just click a button in their favourite IDE and let the program decide or guess what to do and hope for the best.

Absolutely - I was one of them, until my Latex usage became complicated enough that I had to configure custom commands in TexStudio (and of course that necessitated manually running them to test as well).

>My real problem at the moment is the lack of time, so the project is going at a very slow pace at the moment.

No worries, I just thought since I ended up here I might as well leave some feedback, which might be useful at some point in the future. Thanks for the detailed response!

**Comment by vermiculus** [comment]
If we do end up giving such a 'selling points' document that's meant for online viewing, it should probably go in a separate markdown file. The README shouldn't become too long to read and such a document as you suggest has the potential to grow quickly.

**Comment by nlct** [comment]
@Superbest

> Oh, definitely. But I think it would be neat to have a (maybe second?)
> example that shows off an `arara` trick that would be difficult to do
> otherwise. In fact, why not do the same thing in alternative ways so
> visitors can see for themselves how `arara` is helpful? I think it would
> help if the example was a bit more complicated - I suspect it's the less
> simple scenarios that are where `arara` really shines.

If you're interested there are some examples that show off some of 
arara's conditional tricks at 
http://www.dickimaw-books.com/latex/admin/html/arara.shtml For example:

```latex
% arara: pdflatex if changed("tex") || missing("pdf")
% arara: bibtex if (missing("bbl") || found("log", "Citation"))
% arara: pdflatex while (found("log", "Rerun"))
```

**Comment by cfr42** [comment]
Isn't one of the key advantages that the configuration goes with the document and does not depend on the particular IDE or the existence of external scripts. Nor does it rely on my remembering which build option to pick for this file.

For example, I might use an arara tag line for pdfLaTeX with synctex and shell escape for one document; an arara tag for MetaPost for another; and an arara tag with LuaLaTeX without synctex and with restricted shell escape for a third. But I can tell my IDE to compile them all using a single build sequence/shortcut, compile any of them from the command line without even inspecting the file to remember what I need, run them on another machine/OS etc. 

It is the per-file-portable-configuration which makes Arara special.

[I don't use it for Biber etc, because it only seems to like running one command per file, and I never want only Biber ;).]

**Comment by cereda** [comment]
We are all special. :heart: :smiley:

**Comment by mikkelam** [comment]
Great readme now, gj @cereda

**Comment by cereda** [comment]
@mikkelam Hi Mikkel!

Thanks! Kudos to @vermiculus for the huge help. :wink:  And It will be better soon, I promise. This repository will turn upside down, as the manual is half done by now. Lots and lots of new things!

Cheerio!

Paulo
