### ISSUE TITLE
How should rules use `getFullBasename`, if at all?

### ISSUE THREAD

**Issue by vermiculus** [cereda/arara#70]
For mass-builds (like vermiculus/texample, for instance), I think arara could be a fantastic tool. Unfortunately, using

``` sh
$ arara path/to/latex/file.tex
```

doesn't work so well.

Paulo implemented a `getFullBasename` in 360218c7219c13df7a5f32fef3463cb831d913d6 for this purpose, but it's come to light that there are plenty of other considerations. David noted that it's best to cd into the directory first before running LaTeX, but perhaps there are other files that build depends on, _etc._, that are not in that inner directory.

It's a confusing topic, so I thought I'd make an issue out of it for discussion.

**Comment by cereda** [comment]
> [I have no strong feelings one way or the other.](https://www.youtube.com/watch?v=ussCHoQttyQ)

:smile: 

It's a confusing topic indeed. Hopefully the new manual will feature lots and lots of examples (directive and rule-wise), then maybe we could leave rules as they are now and add some alternative rules using the full base name, so users could have local references overriding the default rules if they want to.

I really don't know what else to say. Maybe @nlct has some insights. :wink:

**Comment by cereda** [comment]
I forgot to add two important bits about `arara` in its fourth version. To be completely honest, I had to investigate my own source code in order to understand what my past self had in mind. And apparently, my past self had something hidden under the sleeve. :smile: 

First things first. As we know, `arara` *always* add a rule parameter named `file` which is used to reference the current file. The key point in the fourth version is, `file` will always hold the file name and not its path information. So, `arara foo/bar.tex` will make `file` equals `bar.tex` instead of `foo/bar.tex`. This is by design (`DirectiveUtils`, lines 357 and 389), and `file` is *a string*.

Then, my past self had other plans in his wacky mind, apparently. The fourth version features a (still) undocumented reserved keyword named `reference` which holds the *canonical* path of the provided file (`DirectiveUtils`, lines 356 and 390), as a *File* object. A canonical path is always absolute (the opposite is not always true). So, if `arara foo/bar.tex` only gives `bar.tex` for `file`, we will have `/home/paulo/foo/bar.tex` for `reference`. *Always*.

Why did my past self do this? I think I know why: because the wacky duck had to save the `arara.xml` database file somewhere, and the best place for it is the same level of the processed file. So we would save a lot of guesswork if we manage to find out where in the world <s>is Carmen Sandiego</s> the input file is.

Processing `reference` instead of `file` in the rule scope might be the solution here. This would make `getFullBasename` sound redundant, but it could work the same way. Plus, if we override the `file` value by using the `files` parameter in the directive scope, the `reference` variable remains pristine, so we might need to tackle a string representation again, then `getFullBasename` comes to rescue (some trickery using the parent path from `reference` plus the overriden `file` value). Again, it is a possible and viable solution, but I am still keen on adding notes in the manual than making rules too much extensive; `file` works if we consider `arara` is being called in the top level directory, where the input file resides.

Then we need to consider another aspect introduced in #34, which deals with local configuration files. As I mentioned in the referenced issue, local configuration should be discovered based on the reference file path (the very same value from `reference`), but we will only have it when it's too late. The compromise solution is to exploit the `user.dir` system property which holds the user's current working directory. Then:

```
[paulo@cambridge /home/paulo/Documents] $ arara foo.tex
File reference: /home/paulo/Documents/foo.tex
User's current working directory: /home/paulo/Documents

[paulo@cambridge /home/paulo/Documents] $ arara bar/foo.tex
File reference: /home/paulo/Documents/bar/foo.tex
User's current working directory: /home/paulo/Documents

[paulo@cambridge /home/paulo/Documents] $ arara /home/paulo/foo.tex
File reference: /home/paulo/foo.tex
User's current working directory: /home/paulo/Documents
```

So even the local configuration file feature might suffer if `arara` is not called from the appropriate directory level (either the one holding the configuration file, the one with the input file, or both). This could be a problem or a benefit, you name it. :wink: 

Just for reference, when running `arara` 4.0 with the `--log` option, we can find out a lot of stuff from it (verbose logging):

```
14 jul 2015 21:09:46.033 INFO  - Welcome to arara 4.0!
14 jul 2015 21:09:46.035 INFO  - -----------------------------------------------------------------
14 jul 2015 21:09:46.037 INFO  - ::: arara @ /home/paulo/Testes/arara
14 jul 2015 21:09:46.037 INFO  - ::: Java 1.8.0_45, Oracle Corporation
14 jul 2015 21:09:46.037 INFO  - ::: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-40.b14.fc21.x86_64/jre
14 jul 2015 21:09:46.038 INFO  - ::: Linux, amd64, 4.0.7-200.fc21.x86_64
14 jul 2015 21:09:46.038 INFO  - -----------------------------------------------------------------
14 jul 2015 21:09:46.038 INFO  - Processing 'test.tex' (size: 88 bytes, last modified: 07/14/2015 21:08:37), please wait.
14 jul 2015 21:09:46.042 INFO  - I found a potential pattern in line 1: pdflatex
14 jul 2015 21:09:46.043 INFO  - I found a potential directive: Directive: { identifier: pdflatex, parameters: {}, conditional: { NONE }, lines: [1] }
14 jul 2015 21:09:46.043 INFO  - All directives were validated. We are good to go.
14 jul 2015 21:09:46.043 INFO  - -------------------------- DIRECTIVES ---------------------------
14 jul 2015 21:09:46.043 INFO  - Directive: { identifier: pdflatex, parameters: {reference=/home/paulo/Testes/arara/test.tex, file=test.tex}, conditional: { NONE }, lines: [1] }
14 jul 2015 21:09:46.043 INFO  - -----------------------------------------------------------------
14 jul 2015 21:09:46.044 INFO  - I am ready to interpret rule 'pdflatex'.
14 jul 2015 21:09:46.046 INFO  - Rule location: '/home/paulo/Testes/arara/rules'
14 jul 2015 21:09:46.183 INFO  - I am ready to interpret task 'PDFLaTeX engine' from rule 'PDFLaTeX'.
14 jul 2015 21:09:46.183 INFO  - System command: [ pdflatex, test.tex ]
14 jul 2015 21:09:46.322 INFO  - ---------------------- BEGIN OUTPUT BUFFER ----------------------
14 jul 2015 21:09:46.322 INFO  - This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2014) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `test.tex'.
<*> test.tex
            
(Press Enter to retry, or Control-D to exit)
Please type another input file name: 
! Emergency stop.
<*> test.tex
            
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on texput.log.

14 jul 2015 21:09:46.322 INFO  - ----------------------- END OUTPUT BUFFER -----------------------
14 jul 2015 21:09:46.324 INFO  - Task result: FAILURE
14 jul 2015 21:09:46.326 INFO  - Total: 0.28 seconds
```

As Sean mentions in this issue, a call to

```bash
[paulo@cambridge Testes] $ java -jar arara/arara.jar arara/test.tex 
```

will result in failure, as `test.tex` is not found (should be `arara/test.tex` instead). See the log, `file` holds `test.tex` while `reference` holds the canonical path. I would stick with the rules as they are and suggest users that need to handle different path invocations to override their rules and exploit `reference` instead of `file`; if `files` is used, maybe `getFullBasename` might be a better solution.

Oh my, am I the wacky duck.

**Comment by cereda** [comment]
**Update:** Apparently, I *do* update `reference` when `files` is in use! So things are even better. My past self was a bloody bastard. :wink:

**Comment by cereda** [comment]
Sean, I will close this issue for now and see how `arara` 4.0 goes when it is released soon, in June. Of course, we can reopen it at any time. :wink:
