### ISSUE TITLE
Version 4 installer?

### ISSUE THREAD

**Issue by drozzy** [cereda/arara#75]
Is there any chance you guys might release an installer for windows for Version 4?
It would be fun to start playing with it...

**Comment by cereda** [comment]
To be honest, I am quite reticent to release a beta or RC installer for `arara` 4.0 because, although the code is (to some extend) frozen, the rules are not. In fact, my plan is to revisit every and single rule to provide more options, add some checks and fix potential and existing bugs.

That said, another possibility is to create a Git or Mercurial repository with a snapshot of the current configuration, so instead of providing a installer, one who wants to try the current version should clone the repo and the directory to the path. Updates would also be easier since it would be only a `git pull`, for example. But I wonder how dangerous is to add a repository to the system path. I am not sure I am a certified trusted source. :wink:

**Comment by vermiculus** [comment]
If that's the case, it may be a good idea to implement some sort of rule-update capabilities within arara itself – kinda like tlmgr.

```sh
$ arara --update-rules
Updated rules from 01e8ba to f2400b.
```

Not necessarily using `git pull`, but just a simple wget from [raw.github.com](https://raw.githubusercontent.com/cereda/arara/master/rules/animate.yaml).

**Comment by cereda** [comment]
@vermiculus Yes, it would be surely welcome, but I am afraid only for future releases, like version 5. For now, I am really reluctant in adding something major like that to `arara`, as we need to focus now on rules and the user manual, but this suggestion is a desired feature. :wink: 

To be honest, I wanted to go further on this mechanism, like a `--rules` flag and a couple of keywords that trigger different actions, like adding contributed rule repositories from GitHub or BitBucket, search for specific rules, update individual rules or the entire set, and so forth. I would like to discuss this with the TeX Live folks as well because TeX Live already has an update system and I am not sure how it handles a tool that has life on its own. A good workaround for this issue would be to make updates only available in the user space and freeze the default locations, so TL wouldn't complain about `arara` self-updating without its consent, and `arara` would be able to update rules without interfering with the TL tree. But that's just a thought.

I like the idea very much. My focus is to prepare `arara` 4.0 for release, so people will have a lot of new features to play with, while we secretly work in the background to make this bird even more awesome. :heart:

**Comment by drozzy** [comment]
@cereda I see no reason why installer would be a bad thing :-) You can always put up a new version of the installer if the thing changes significantly. 

Also, imo, it would be better to release the version whatever it may be, so people would start submitting  pull requests. I highly recommend C4 process: http://rfc.zeromq.org/spec:22 which is pretty liberal with contributions.

**Comment by cereda** [comment]
Version 4.0 is now released! :package: 

The packaged version is in our [release](section) and CTAN will be updated accordingly within the next 24 hours. Hopefully TeX Live and MiKTeX will update their versions in a couple of days!

**Comment by drozzy** [comment]
"release" link broken ... :(

**Comment by cereda** [comment]
Ouch, deeply sorry @drozzy!

I forgot to add the correct link here! Now it is fixed!
