### ISSUE TITLE
Check for changes in included files

### ISSUE THREAD

**Issue by samcarter8** [cereda/arara#82]
What I am basically looking for is something like `changed('*.tex')`. To start easy I wanted to do this with one file. From the description in https://github.com/cereda/arara/wiki/New-feature-highlights-in-4.0

>  `changed(file)`: the very same idea as the previous method, but with a proper File object instead.

I understand that it should be possible to give a specific file. But while `changed('tex')` works flawlessly to check for changes of my main file, I tried `changed('document.tex')`, but this does not trigger arara.

My `main.tex`:

```
% arara: pdflatex if changed('document.tex') 

\documentclass{article}

\begin{document}
\include{document}
\end{document}
```
and the `document.tex`:

```
test
```

![What am I doing wrong?](https://cloud.githubusercontent.com/assets/8226363/18590441/1da246c0-7c2f-11e6-8eb3-d168d4a11064.jpg)

**Comment by cereda** [comment]
Man, I simply love these ducks! :wink: 

A brief explanation of what's happening: `changed(String)` takes the provided argument, considers it as a file extension and applies to the main file base name. So, having `main.tex` as your main document, `changed('aux')` implies checking for modifications in `main.aux`. When using `changed('document.tex')`, the method will look for `main.document.tex`, which is not what you want.

However, do not despair, young grasshopper! There's a second `changed(...)` method which takes the argument type into consideration: `changed(File)` will check for modifications directly in that file! Well, how does one use this marvellous contraption?

The secret lies on another helper method in the directive context, `toFile(String)`, which takes a string representing your file and returns a file representation of it! That's why I really need to work on the user manual, there are so many new features and improvements in version 4.0! Your new directive might work now:

```tex
% arara: pdflatex if changed(toFile('document.tex'))
```

Hope it helps! Quack! :wink:

**Comment by samcarter8** [comment]
Thanks for your lightning-fast reply! That solves the mystery!

**Comment by cereda** [comment]
My pleasure, pal! I am glad your experience with version 4.0 is being so positive! All the best! :wink:
