### ISSUE TITLE
Subdirectories not working

### ISSUE THREAD

**Issue by maetra** [cereda/arara#84]
Subdirectories are currently not working in the master (4.0), the source of the problem lies in `DirectiveUtils`

```
File representation = CommonUtils.getCanonicalFile(String.valueOf(file));
map.put("reference", representation);
map.put("file", representation.getName());
```
as `getName()` only returns the file name and no subdirectory, a quick fix would be to change the last line to `map.put("file", String.valueOf(file));`

**Comment by cereda** [comment]
Hello there! Thank you very much for the feedback!

This is a very tricky report! I'd say not handling subdirectories is technically my fault, but it was a calculated risk. This behaviour was *by design*.

Since the first version, `file` is a String representation of the file name. If I recall correctly, it was an exact reproduction of what the user had provided in the command line, e.g,

| CLI invocation | Mapping |
| ---------------------------|--------------------------|
| `arara foo.bar` | `file = foo.bar` |
| `arara baz/foo.bar` | `file = baz/foo.bar` |
| `arara /usr/lib/foo.bar` | `file = /usr/lib/foo.bar` |

 So far, it worked as expected since `arara` had a very small audience. Then things started to get a bit complicated, as people started to pay attention to the tool. Consequently, `file` became a very fragile orb, to the point of causing headaches to me as a developer and to lots of users.

For this version, `reference` was introduced as a means to solve the location issue. While `file` is just a string containing the file name (without any path information), `reference` is a (Java) `File` object holding the canonical path of this file. This means, e.g,

| CLI invocation | Mapping |
| ---------------------------|--------------------------|
| `arara foo.bar` | `file = foo.bar`, `reference = /home/paulo/foo.bar` |
| `arara baz/foo.bar` | `file = foo.bar`, `reference = /home/paulo/baz/foo.bar` |
| `arara /usr/lib/foo.bar` | `file = foo.bar`, `reference = /usr/lib/foo.bar` |

By doing this, I keep `file` as the file name while `reference` holds the complete, *correct*, corresponding path. It's a way I found to make the tool more robust and less error prone. It is nice to note that hashing features of this new version use and abuse these references.

As *mea culpa*, `file`'s behaviour is now different from older versions, but the old way is, to the extent of my poor knowledge, very troublesome to keep around. At least, now things can be more concise and also trackable.

As you found by yourself, things broke. And that's bad, *really* bad. I am sorry. But nothing is lost, as it's a nice timing for us to look for a solution, as everything we need to fix is already available to us in the rule scope.

*(I also need to apologize for the lack of updates in this project. I am still working on my thesis and days have been hectic.)*

I have a couple of suggestions:

1. Replace `file` by `reference` in all rules. This approach will mostly certainly fix this issue without any huge efforts. Then commands will run on *absolute* files, not relative ones. I don't know if we might end up with potential side effects of this approach. For example,

    ```java
    return getCommand('pdflatex', interaction, draft, shell, synctex, options, reference)
    ```

    is now used instead of the current

    ```java
    return getCommand('pdflatex', interaction, draft, shell, synctex, options, file)
    ```

    It's important to know the concept of a working directory, as `arara` uses the one it's being invoked from. Again, I don't know if any tool might complain about (specially TeX engines, as they don't like the idea of subdirectories).



2. There's a new command in which we can specify the current working directory, so we can keep `file` as it is, but include the parent reference of it. In other words, we could replace, e.g,

    ```java
    return getCommand('pdflatex', interaction, draft, shell, synctex, options, file)
    ```

    by this new method invocation:

    ```java
    return getCommandWithWorkingDirectory(
        reference.getParent(),
        'pdflatex', interaction, draft, shell, synctex, options, file
    )
    ```

    There is something very interesting about this approach: commands will run on *relative* files, but from an absolute directory reference. It's quite the opposite approach! And it works (in theory, as I haven't tested it yet)!

I've never expected `arara` would gain so much visibility and that rules and work flows would become so intricate! Hopefully, we could make things work in the end.

I am deeply sorry if my previous thoughts haven't reached your initial expectations, so I'd love to hear from you if these ideas and suggestions make any sense. Also, thank you very much for trying `arara`, I hope you enjoy the philosophy behind it!

I am the culprit, as no manual is available at the moment. The tool took a quantitative and qualitative step from previous versions and there's a plethora of new features and bug fixes. But then a starving student has a thesis to write, and everything else had to be put on hold. Hopefully, I will survive in the end!

Again, thanks for the feedback! Also, happy belated Thanksgiving!

**Comment by maetra** [comment]
First of all, a huge thank you for all the work you put into `arara`! No need to be apologetic at all! I am a fully aware that I am running an unreleased version where things can be broken. So I am just very happy to be able to use `arara `👍  

Just as a quick sidestory, I was trying to get indent to work with miktex but there is no `indent` rule with the current miktex release (is there a reason for that?), so I decided to compile from the latest master. After loading the necessary libraries, I had trouble with `messages.getMessage()` commands that caused runtime errors. As I commented them out, I was able to debug arara. 

To me your suggestions both make sense. I don't know if using absolute paths can sometimes be a problem e.g. when a path contains spaces? And I am not sure if the second approach might have caveats, e.g. running bibtex with a bibfile e.g. `working directory/literature/bibfile.bib` in one directory and the aux file in another `working directory/thesis.aux`? 

Happy belated Thanksgiving to you as well! 

PS: As I am interested in speeding up my compilation as mentioned [here](https://tex.stackexchange.com/questions/287662/using-arara-as-a-latex-build-tool-with-different-output-directory), can you give me a hint where I need to look?

**Comment by alerque** [comment]
I'm using arara 3.0a (that came with my texlive distro) and cannot get subdirectories working either. The `@{file}` orb only has the filename, no path, and there is no `@{reference}` orb at all. What gives? What is the point of having a `@{getDirname(file)}` if `file` never has a path on it? What other way can I use to get the path of a file argument into my command?

**Comment by cereda** [comment]
Hello @alerque! Sorry for the potentially quick message. I am now at a TUG meeting.

I have some pointers:

1. `reference`is featured in series 4. This particular variable holds a `File` object. Path is actually a consequence of it, although under the hood we try to keep them absolute and canonical.

2. `file` is a string, and holds what is passed as argument to the tool (at least, in a first moment). If you say `foo/bar.tex`, `foo` is also part of the value. The problem is that most TeX tools were build to have files at the same level to work.

It is definitely possible to make things work for version 3.0, as the underlying scripting language offer this. However, a new rule has to be written for it. My bet would be creating a proper `File` object and manipulate it to achieve your specific goals.

**Comment by alerque** [comment]
I gathered from the above that `reference` was a v4 only thing. The trouble is that `file` in v3 is _not_ providing me the argument passed to the tool. I've tried this with a very basic rule that does nothing but echo back the value of `@{file}` and played with it quite a bit. I can't get anything inside of arara to give me the actual value of the argument passed to it.

I'm not quite sure what you mean by writing a new rule or a "proper `File` object". I mean I know what arara rules are and understand the basic concept of objects, but I don't see how those things combine to get me what I need. This isn't a TeX limitation because all the commands I need arara to run for me work fine when given an `/absolute/path/to/file.tex`, I just need arara to pass this along when called with `arara /absolute/path/to/file.tex`.

(Note this is part of a 'live' CI build system that watches file system nodes and rebuilds things the moment they change on disk. I can (and have) written a wrapper script that hacks around this limitation, but the implementation is dirty and I'm trying to get rid of it.)

**Comment by cereda** [comment]
@alerque Sorry for not being able to reply right now. I am a bit busy at the moment. I will return back to your question on Monday afternoon when I arrive from Rio de Janeiro.

**Comment by TheTeXnician** [comment]
This will be closed because subdirectory handling is status-by-design.

Please note, that arara v5.0 will feature working directory support, so you can start arara with `arara -d /absolute/path file.tex` and then it will work within the subdirectory. The release is scheduled to happen before the DANTE Frühjahrstagung.
