### ISSUE TITLE
Updates to indent.yaml

### ISSUE THREAD

**Issue by cmhughes** [cereda/arara#87]
Hello arara team!
Thanks for all of your work on the awesome arara tool :)

I'm nearly ready to release version 3.0 of `latexindent.pl`, and wondered if a few updates to `indent.yaml` could be made (https://github.com/cereda/arara/blob/master/rules/indent.yaml). 

updates to existing switches
-
I've made a small change to the `-o` flag so that it works in a more logical way, and the output file is tied to the `-o` switch; for example, the following syntax is now appropriate:

`latexindent.pl myfile.tex -o=myoutputfile.tex`

The `-l` switch can now take an *optional* argument; for example, the following are both allowed:

`latexindent.pl myfile.tex -l`

`latexindent.pl myfile.tex -l=myymal.yaml`

new switches
-
There's a few new switches to be added to the rule, if that's ok:

- `-m` switch for `modifylinebreaks` this switch doesn't take any arguments, it's just on/off
- `-g=name.log` for the name of the logfile; this switch *needs* an argument

Does `indent.yaml` now ship with `arara` in `texlive` and `MiKTeX`?

I hope that these updates sound ok; do let me know if I can do anything to help.
Thanks again
Chris

**Comment by EngCat** [comment]
> Does indent.yaml now ship with arara in texlive and MiKTeX?

No, it doesn't.

**Comment by cereda** [comment]
Hello, Chris!

First of all, apologies for the huge delay in replying to this issue. I've probably seen it, but forgot to reply to it. I am so sorry.

Regarding the new updates, they are all possible. 😉 I will try to update the `indent.yaml` rule accordingly, as soon as possible.

Regarding shipping `indent.yaml`, it's not available in TL, because there were no updates in `arara` since its original release. Hopefully, the new release will fix that, as the tool will ship with lots of new rules. I plan to update more rules when 4.0 is out, as we have a better rule framework going on.

I will update this issue when a new rule is posted.

Cheers!
