### ISSUE TITLE
Error in xelatex rule

### ISSUE THREAD

**Issue by pat-s** [cereda/arara#92]
Just freshly installed v4 (coming from 3) and getting the following error:

```
I have spotted an error in rule 'xelatex' located at
'/home/pjs/.local/bin/rules'. I found these unknown keys in the
directive: (action). This should be an easy fix, just remove them
from your map.
```

Is the error on my side? Wondering that no one else reported xelatex rule issues so far if there would be such :ear:

**Comment by cereda** [comment]
Hello!

Thankfully that's an easy fix! 😄 

The `action` key was updated to `interaction` in version 4.0, so try updating your `xelatex` directive in your document to:

```tex
% arara: xelatex: { interaction: batchmode }
...
```

Note that `batchmode` is just an example, it can be `nonstopmode`, `scrollmode` or `errorstopmode`. 😉 

Let me know if it works! And thanks for trying out version 4.0!

**Comment by pat-s** [comment]
Oh hey, quick reply :+1: 

Indeed, that solved the problem - I spent a lot of time searching in the rule file for "action" but not in the Tex :disappointed: 

While still here, I get an additional error for which I do not want to open a new issue:

```
arara files/cv.tex --verbose
  __ _ _ __ __ _ _ __ __ _ 
 / _` | '__/ _` | '__/ _` |
| (_| | | | (_| | | | (_| |
 \__,_|_|  \__,_|_|  \__,_|

Processing 'cv.tex' (size: 6 KB, last modified: 10/27/2017
15:06:09), please wait.

-----------------------------------------------------------------
(XeLaTeX) XeLaTeX engine
-----------------------------------------------------------------
This is XeTeX, Version 3.14159265-2.6-0.99998 (TeX Live 2017/Arch Linux) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
! I can't find file `cv.tex'.
<*> cv.tex
          
(Press Enter to retry, or Control-D to exit)
Please type another input file name
! Emergency stop.
<*> cv.tex
```
Looks weird to me because at first `cv.tex` is found by `arara` and then XeLaTeX complains about not finding it?

**Comment by cereda** [comment]
Oh no worries, that's why version 4.0 is still in the works: I need a proper manual to indicate the valid keys for each rule! 😉 

Feel free to use this issue to report any further... issues 😃 , it is always great to have feedback!

Regarding XeLaTeX not finding `cv.tex`, we are both right and wrong at the same time. 😉 In the rule, we usually resort to just the file name (represented by `file`), so any additional path is stripped off. Then `files/cv.tex` becomes `cv.tex`, so when `xelatex` is invoked, the file does not exist in the current directory.

There's been a debate in the TeX community (not just by the `arara` team) whether a file should be invoked within a directory other than the working one. I've seen some cases where the engine go wacky and simply ignore locations. Relative paths are usually a sensitive subject, as well as spaces in file names. 😉 

Being aware of this scenario, I offer a couple of possibilities (again, they must be in the upcoming documentation, but for now I have a thesis to write!):

- Replace `file` by `reference` (I foresaw this issue long time ago) in the rule. The `reference`... reference 😄  keeps the canonical path of the file, so it might get things right. The engine would be called with a full reference to the file (which might work or not, again, this is a sensitive topic, but `arara` would be passing the correct reference).
- Specify the working directory when issuing the command in the rule. It could be discovered from the `reference`... reference 😄 . In your example, the tool would "enter" the `files` directory and then call `xelatex` on `cv.tex`, which would work.
- There might be one or two more possibilities, but that's what I can think of at the moment. 😋 

For now, could you please edit `rules/xelatex.yaml` and replace (line 16):

```
return getCommand('xelatex', interaction, shell, synctex, options, file)
```

by

```
return getCommand('xelatex', interaction, shell, synctex, options, reference)
```

It should work now. 😉 

Cheerio!

**Comment by pat-s** [comment]
Hi @cereda ,

for now I simply did a `cd` into the respective directory to get it working. 
However, thanks for your always very detailed answers!

**Comment by cereda** [comment]
My pleasure, Patrick! Let me know if I can be of help! I will also reference this issue when discussing file name versus full paths. 😉
