### ISSUE TITLE
Clean rule not removing files?

### ISSUE THREAD

**Issue by pat-s** [cereda/arara#94]
With `v4` my code looks as follows:

```
% arara: clean: { files: [ elsearticle-template.aux, elsearticle-template.bbl ] }
% arara: clean: { files: [ elsearticle-template.bcf, elsearticle-template.cod ] }
% arara: clean: { files: [ elsearticle-template.blg, elsearticle-template.lof ] }
% arara: clean: { files: [ elsearticle-template.lot, elsearticle-template.out ] }
% arara: clean: { files: [ elsearticle-template.toc, elsearticle-template.log ] }
% arara: clean: { files: [ elsearticle-template.run.xml ] }
```

Although the rule succeeds, the files are still there. Am I using it wrong with v4?

**Comment by cereda** [comment]
Hello, Patrick!

That is an odd behaviour, we need to investigate! 😄 

We have two methods:

1. Run `arara` with `--log` and inspect the resulting `arara.log` file, looking for the removal command. The log file might have some interesting clues on what's going on.

2. Run `arara` with `--dry-run` and inspect the terminal output. This option just "simulates" the execution. The system commands will be displayed in the terminal.

Personally, I recommend method 1, as it's more detailed. Could you paste the log here? 😉 

Thanks!

**Comment by pat-s** [comment]
Log looks fine at a first glance (I only posted the first two, `.aux` and `.bbl`). 
However, files are not removed. Any idea? :)

```
02 Nov 2017 15:36:24.065 INFO  - ----------------------- END OUTPUT BUFFER -----------------------
02 Nov 2017 15:36:24.066 INFO  - Task result: SUCCESS
02 Nov 2017 15:36:24.066 INFO  - I am ready to interpret rule 'clean'.
02 Nov 2017 15:36:24.066 INFO  - Rule location: '/home/pjs/.local/bin/rules'
02 Nov 2017 15:36:24.090 INFO  - I am ready to interpret task 'Cleaning feature' from rule 'Clean'.
02 Nov 2017 15:36:24.091 INFO  - System command: [ rm, -f, elsearticle-template.aux ]
02 Nov 2017 15:36:24.098 INFO  - ---------------------- BEGIN OUTPUT BUFFER ----------------------
02 Nov 2017 15:36:24.099 INFO  - 
02 Nov 2017 15:36:24.099 INFO  - ----------------------- END OUTPUT BUFFER -----------------------
02 Nov 2017 15:36:24.100 INFO  - Task result: SUCCESS
02 Nov 2017 15:36:24.100 INFO  - I am ready to interpret rule 'clean'.
02 Nov 2017 15:36:24.100 INFO  - Rule location: '/home/pjs/.local/bin/rules'
02 Nov 2017 15:36:24.108 INFO  - I am ready to interpret task 'Cleaning feature' from rule 'Clean'.
02 Nov 2017 15:36:24.108 INFO  - System command: [ rm, -f, elsearticle-template.bbl ]
02 Nov 2017 15:36:24.112 INFO  - ---------------------- BEGIN OUTPUT BUFFER ----------------------
```

**Comment by cereda** [comment]
(first time replying to an issue by email, let us see how it goes)

My second guess would be the same scenario we had with the engine. Is the 
file located in the current directory? If not, we have found the reason. 😀 
All rules so far use the filename instead of a reference...


A 2 de novembro de 2017 12:41:45 PM, Patrick Schratz 
<notifications@github.com> escreveu:

**Comment by pat-s** [comment]
*facepalm* :sheep: 

It was a typo addressing the file name in the `clean` rule call...

Now everything works, thanks for helping me out again. Now there might be some quiet times ahead - hopefully :smile:

**Comment by cereda** [comment]
Oh glad to know it worked! 😉 

I must point out that `clean` behaves quite differently from other rules. It takes the entries from the directive and treats them as literal paths, so, e.g:

```tex
% arara: clean: { files: [ foo.bar, baz/foo.bar ] }
```

In this example, `arara` will run `rm` (or `del` if you are in a Windows machine) on `foo.bar` in the current working directory and another `foo.bar` inside a `baz` directory. The reason for `arara` always returning `SUCCESS` for `clean` is the presence of a `-f` (or `--force`) flag in the `rm` command, so if the file is not found, there's no reason for complaining about it (we were about to remove it anyway).

It is worth mentioning that if `foo` is your base name, from version 4.0 on, you can remove files based on extension, so, e.g:

```tex
% arara: clean: { extensions: [ aux, log, toc ] }
```

In this case, `foo.aux`, `foo.log` and `foo.toc` will be removed. 😉

**Comment by pat-s** [comment]
That's cool and saves some code lines - I will change my code :) 

I also think that arara would deserve some promotion but promoting tex stuff is not easy. 

Also an AUR package would be nice - maybe I have some time to help you guys :)

**Comment by cereda** [comment]
Thanks for the kind words, Patrick. 😉 

The real issue for now is the lack of a proper manual. Since version 4.0 was a complete rewrite of the previous versions, with a lot of new features, enhancements and bug fixes, it deserves a new instruction booklet. 😉 Sadly, I am now stuck with a thesis to write, so I have to focus on finishing it, otherwise I will be in the academic limbo! My plan is to work on the manual as soon as possible. There's a lot of expectation for version 4.0 getting a talk on TUG 2018, to be held in Rio de Janeiro, so I am looking forward to it.

I don't know much about Arch packaging, but it would be great to have options for our users. 😉

Another thing that I need to work on sooner or later is the call for translations. So far, version 4.0 has localized messages in 4 languages, namely English (default), German, Dutch (new addition!) and an amusing Norfolk dialect. Last version had Russian, French, Italian and Brazilian Portuguese as well. My plan is to have them back in this version with a possible addition of much more!

Let us see how things go in the long run... 😉
